### ISSUE TITLE
tabular format output

### ISSUE THREAD

**Issue by jrperritt** [jrperritt/rack#1]
I'm not sure there's a way to generalize the tabular output for the different commands. Tables are tricky because they have different headers, different value types, sometimes we'll want a nested value, etc. We'll be able to extract the shell of the table, but the headers and values may have to be command-specific.

**Comment by rgbkrk** [comment]
Tables are cool, so long as they aren't as super-formatted like nova. It's harder to use with tools like `cut` and `grep` (`grep -v` will show the dividers for instance).

**Comment by jrperritt** [comment]
@rgbkrk Are you working on a minimal, `docker ps`-like, tabular output?

**Comment by rgbkrk** [comment]
Yeah, let me take this one.

**Comment by jrperritt** [comment]
After coding #20 , I'm thinking that by default the table should be with a border, but that we provide a `noborder` flag that will be minimal. See here: https://github.com/jrperritt/rack/pull/20/files#diff-84efe558aa2959a3e15e43a6eba8a1b1R100

**Comment by jrperritt** [comment]
Closing this. I think we've got a handle on the table format thanks to @rgbkrk

**Comment by rgbkrk** [comment]
I'm so persnickety. Thanks for fighting through it with me.

:heart_decoration:
