### ISSUE TITLE
Windows config produced no results

### ISSUE THREAD

**Issue by DonSchenck** [jrperritt/rack#109]
1. Installed on my Windows machine.
2. Moved to C:\tools
3. Added C:\tools to %PATH%
4. Ran rack configure - Entered stuff
5. ran rack servers instance list

got

PROPERTYVALUE
error Error creating ProviderClient: You must supply a Username in your AuthOptions.

Checked: C:\tools\.rack directory DOES NOT exist.

**Comment by DonSchenck** [comment]
Windows 8.1

**Comment by carolynvs** [comment]
@DonSchenck The .rack directory should have been created in your user directory, e.g. C:\Users\DonSXXX\.rack.  Can you check there?

**Comment by DonSchenck** [comment]
Yes; that's where it was created.

**Comment by carolynvs** [comment]
I think you are running into the same issue as me #111. Want to check that out?

**Comment by DonSchenck** [comment]
No; the issue was that it was creating the config in the C:\Users\Don\.rack folder, and wasn't searching there when running ```rack foo```

**Comment by carolynvs** [comment]
Doh! I was hoping that they were related. Carry on! :smile:

**Comment by DonSchenck** [comment]
Whatever was changed ... this issue is NO LONGER AN ISSUE. 

Working fine now.

**Comment by jrperritt** [comment]
:+1: closing
