### ISSUE TITLE
setup file

### ISSUE THREAD

**Issue by jrperritt** [jrperritt/rack#11]
Though the binary will be all-inclusive, bash completion, at least at the moment, has to be activated manually. We may want to write a script that will do it.

**Comment by jrperritt** [comment]
Command completion is the only thing I can think of that would need to be initialized. How about a command like `rack init` or `rack init command-completion` to set up the (at the moment, only bash) completion?

**Comment by kenperkins** [comment]
@jrperritt is looking at this today.

**Comment by jrperritt** [comment]
closed by #143
