### ISSUE TITLE
Default profile name is case sensitive (Windows)

### ISSUE THREAD

**Issue by carolynvs** [jrperritt/rack#111]
Run `rack configure`

```Batchfile
c:\>rack configure

This interactive session will walk you through creating
a profile in your configuration file. You may fill in all or none of the
values.

Rackspace Username: username
Rackspace API key: apikey
Rackspace Region : IAD
Profile Name: default
```

This creates my config file in C:\Users\caro8994\.rack\config
```
[default]
username = username
apikey = apikey
region = IAD
```
NOTE: The line endings are funky, sometimes using just \r and not \r\n.
![config-line-endings](https://cloud.githubusercontent.com/assets/1368985/8358987/225d9f7e-1b29-11e5-94cd-7d41b3f6ca04.png)

2. Run `rack servers instance list`. Fails because it can't find the proper authentication credentials.
3. Run `rack --profile default servers instance list`. Works fine.
4. Modify the config file to make the profile name all upper case, [DEFAULT].
5. Run `rack servers instance list`. Works fine.

I _thought_ that the other week when I did this same process that the cli picked up my profile correctly without the upper-casing.

**Comment by carolynvs** [comment]
When I run `rack configure` and leave the profile name empty (just press ENTER), it doesn't save the profile name correctly.

```
[]
username = XXX

apikey = XXX
region = IAD
```

**Comment by jrperritt** [comment]
Hmm, I wonder if we need to trim all the space around the profile name.

**Comment by jrperritt** [comment]
@carolynvs Did trimming the white space around the profile name fix this issue?

**Comment by carolynvs** [comment]
@jrperritt  The latest rack.exe linked from readthedocs doesn't appear to have any changes. Where should I be getting this change from to try out?

**Comment by jrperritt** [comment]
I think this has been resolved. Closing.
