### ISSUE TITLE
command names for block storage and security groups

### ISSUE THREAD

**Issue by jrperritt** [jrperritt/rack#130]
Currently, all command names are all-one-word: `blockstorage`, `securitygroups`, `securitygrouprules`.

The alternative would be kebab-case like we do for flags: `block-storage`, `security-groups`, `security-group-rules`

This isn't a terribly important question, because it only affects the command's aesthetics.

**Comment by kenperkins** [comment]
I quite like kebab-case for them. `rack networks security-groups list` seems nicer, and more consistent with our other UX.

**Comment by kenperkins** [comment]
Accidental close.

**Comment by jrperritt** [comment]
Yeah, I think I like that better, too.

**Comment by kenperkins** [comment]
We've implemented this as described above; leaving open for any further commentary. No action to do for MVP.

**Comment by rgbkrk** [comment]
Thanks for updating those to kebab case.
