### ISSUE TITLE
Include environment variable names in output when no config specified/present

### ISSUE THREAD

**Issue by rtgoodwin** [jrperritt/rack#132]
Some great improvements made here, but can we go the final mile and:

- list the actual env var names (i.e. RACK_USER_IFORGET_WHAT_IT_IS)
- Suppress the PROPERTYVALUE header in the output?

A super bonus win would be to actually give them advice on storing the vars, just like the bash completion stuff will, but I know of no easy cross platform way to do it, so let's skip it for now.

**Comment by jrperritt** [comment]
closed by https://github.com/jrperritt/rack/commit/9f2c048
