### ISSUE TITLE
Rename to rack

### ISSUE THREAD

**Issue by everett-toews** [jrperritt/rack#14]
The current name rackcli is quite redundant. Imagine typing "rackcli" on the CLI over and over and over, thousands of times in your careers as an operator or support floor admin. Sooner than later the redundancy of typing "cli" on the CLI will become painful. It's a papercut we can avoid.

Also note how no other CLI app ever has appended "cli" to the actual command name.

The package name also appears to be available!

http://packages.ubuntu.com/search?keywords=rack&searchon=names&suite=trusty&section=all

and

    $ brew install rack
    Error: No available formula for rack
    Searching formulae...
    aircrack-ng	  cracklib-words    git-tracker	      lcrack		nutcracker	  pdfcrack	    tcptrack
    cracklib	  fcrackzip	    httrack	      ncrack		ophcrack	  plt-racket	    truecrack
    Searching taps...
    Caskroom/cask/8tracksradiohelper		Caskroom/cask/klystrack				Caskroom/cask/racket
    Caskroom/cask/actotracker			Caskroom/cask/loadmytracks			Caskroom/cask/rubitrack
    Caskroom/cask/brackets				Caskroom/cask/mactracker			Caskroom/cask/time-tracker
    Caskroom/cask/charlessoft-timetracker		Caskroom/cask/milkytracker			Caskroom/cask/track-o-bot
    Caskroom/cask/kensington-trackball-works	Caskroom/cask/pokertracker			Caskroom/cask/youtrack-workflow

We are the rack. Let's name our kickass CLI "rack".

**Comment by jrperritt** [comment]
:+1: Done here: https://github.com/jrperritt/rack/commit/f30ee85a5442b1e731d1ce3de861f2add833a7bf

**Comment by everett-toews** [comment]
:boom: 

Thanks!
