### ISSUE TITLE
reproducable builds

### ISSUE THREAD

**Issue by flazz** [jrperritt/rack#140]
Hi, (RE Experience the new Rackspace Cloud CLI and win prizes!)

Your deps (44) are a moving target. Has the project decided on a vendoring or dep tool? If not would you like a PR with everything locked down?

* github.com/codegangsta/cli
* github.com/fatih/structs
* github.com/mitchellh/mapstructure
* github.com/rackspace/gophercloud
* github.com/rackspace/gophercloud/openstack
* github.com/rackspace/gophercloud/openstack/blockstorage/v1/snapshots
* github.com/rackspace/gophercloud/openstack/blockstorage/v1/volumes
* github.com/rackspace/gophercloud/openstack/compute/v2/extensions/bootfromvolume
* github.com/rackspace/gophercloud/openstack/compute/v2/extensions/diskconfig
* github.com/rackspace/gophercloud/openstack/compute/v2/extensions/keypairs
* github.com/rackspace/gophercloud/openstack/compute/v2/flavors
* github.com/rackspace/gophercloud/openstack/compute/v2/images
* github.com/rackspace/gophercloud/openstack/compute/v2/servers
* github.com/rackspace/gophercloud/openstack/identity/v2/tenants
* github.com/rackspace/gophercloud/openstack/identity/v2/tokens
* github.com/rackspace/gophercloud/openstack/identity/v3/tokens
* github.com/rackspace/gophercloud/openstack/networking/v2/common
* github.com/rackspace/gophercloud/openstack/networking/v2/extensions/security/groups
* github.com/rackspace/gophercloud/openstack/networking/v2/extensions/security/rules
* github.com/rackspace/gophercloud/openstack/networking/v2/networks
* github.com/rackspace/gophercloud/openstack/networking/v2/ports
* github.com/rackspace/gophercloud/openstack/networking/v2/subnets
* github.com/rackspace/gophercloud/openstack/objectstorage/v1/accounts
* github.com/rackspace/gophercloud/openstack/objectstorage/v1/containers
* github.com/rackspace/gophercloud/openstack/objectstorage/v1/objects
* github.com/rackspace/gophercloud/openstack/utils
* github.com/rackspace/gophercloud/pagination
* github.com/rackspace/gophercloud/rackspace
* github.com/rackspace/gophercloud/rackspace/compute/v2/flavors
* github.com/rackspace/gophercloud/rackspace/compute/v2/images
* github.com/rackspace/gophercloud/rackspace/compute/v2/keypairs
* github.com/rackspace/gophercloud/rackspace/compute/v2/servers
* github.com/rackspace/gophercloud/rackspace/identity/v2/tokens
* github.com/rackspace/gophercloud/rackspace/networking/v2/common
* github.com/rackspace/gophercloud/rackspace/networking/v2/networks
* github.com/rackspace/gophercloud/rackspace/networking/v2/ports
* github.com/rackspace/gophercloud/rackspace/networking/v2/security/groups
* github.com/rackspace/gophercloud/rackspace/networking/v2/security/rules
* github.com/rackspace/gophercloud/rackspace/networking/v2/subnets
* github.com/rackspace/gophercloud/rackspace/objectstorage/v1/containers
* github.com/rackspace/gophercloud/rackspace/objectstorage/v1/objects
* github.com/rackspace/gophercloud/testhelper
* github.com/rackspace/gophercloud/testhelper/client
* gopkg.in/ini.v1

**Comment by jrperritt** [comment]
@flazz Yes, that's true. We haven't decided on vendoring vs Godep yet. What are your thoughts on the matter?

**Comment by jnoller** [comment]
+1 to vendoring

**Comment by flazz** [comment]
+1 vendoring; its bulletproof

**Comment by jrperritt** [comment]
Looks like the ayes have it. A PR for vendoring would be great @flazz

**Comment by flazz** [comment]
on it …

**Comment by flazz** [comment]
can we consider this closed?

**Comment by jrperritt** [comment]
Yes, I think so. Closed by #142 . Thank you, @flazz :smile:
