### ISSUE TITLE
authentication endpoint

### ISSUE THREAD

**Issue by jrperritt** [jrperritt/rack#15]
Is this the only authentication endpoint now: https://identity.api.rackspacecloud.com/v2.0?
If so, we can remove the `RS_AUTH_URL` from the required parameters the user has to set.

**Comment by jnoller** [comment]
Yes; but they still need to be able to override it to point to staging and elsewhere via the environment or ini file

**Comment by jrperritt** [comment]
Ok. Is it satisfactory to assume that endpoint if one doesn't exist in envvars/ini/keyring or should it be mandatory?

**Comment by jnoller** [comment]
Yes, sensible defaults

Jesse

**Comment by jrperritt** [comment]
:+1:
