### ISSUE TITLE
networks network create inconsistency

### ISSUE THREAD

**Issue by rgbkrk** [jrperritt/rack#159]
I was a little surprised by

```
$ rack networks network create
PROPERTY	VALUE
ID		9377e7c4-0411-410f-b28d-e1e4be3d1867
Name
Up		true
Status		ACTIVE
Shared		false
Tenant ID	932445
```

because the other APIs tend to show you help on a `create` call, allowing for accidental exploration.

Feature or bug?

**Comment by kenperkins** [comment]
I think bug. It's dangerous to allow resource creation with no arguments. I wonder what other APIs allow it without any arguments.

**Comment by jrperritt** [comment]
There are no required flags to create a network. It's not a bug.

**Comment by kenperkins** [comment]
Absent requiring a name, which is not required, what more could we do here?

**Comment by kenperkins** [comment]
We should punt this until at least after public beta.

The behavior within `rack` is technically correct, as we're handicapped by a shitty cloud API. We're open to suggestions on how to address this, but I don't think we need to do anything for public beta.

Thoughts?

**Comment by jrperritt** [comment]
Unless there are any objections, we'll just require the `--name` flag.

**Comment by kenperkins** [comment]
w00t.

```
/data/src/rack [master] $ rack networks network create
error	Missing flag: --name is required.
```
