### ISSUE TITLE
Add commit hash to binary metadata

### ISSUE THREAD

**Issue by kenperkins** [jrperritt/rack#162]
How do/if we version individual commits to master
How do we handle official releases, etc.

**Comment by rgbkrk** [comment]
So far we've agreed that SemVer is awesome.

**Comment by rgbkrk** [comment]
Also noted from the meeting:

* See if we can stick the commit hash in the binary on build

**Comment by kenperkins** [comment]
Desired output:

```bash
$ rack --version
rack version 1.0.0
commit: de2f457196e307fde89496385abdecbc01bb528d
```

**Comment by rgbkrk** [comment]
I have a terrible branch that I did this in, as well as an experimental setup to provide this to go packages in https://github.com/rgbkrk/fromthegitgo

**Comment by rgbkrk** [comment]
Apparently I have uncommitted things here too. I generally want this as a tool and will have it ready for `rack` as well.
