### ISSUE TITLE
Man page

### ISSUE THREAD

**Issue by rgbkrk** [jrperritt/rack#163]
Autogenerate a man page based on our cli commands.

**Comment by kenperkins** [comment]
Agree that we need to do this, but we are already heavily scheduled for the first public MVP.

**Comment by rgbkrk** [comment]
Closed by #198.

**Comment by jrperritt** [comment]
Not quite closed yet since it will only build for one of the platforms.

**Comment by rgbkrk** [comment]
@kenperkins totally made me comment somewhere to confirm his email rules. Don't forget to @ mention him in all issues.

**Comment by kenperkins** [comment]
asshole

**Comment by kenperkins** [comment]
@rgbkrk is at my house and has clearly compromised my credentials over my wifi.
