### ISSUE TITLE
Prevent leakage from Gophercloud errors

### ISSUE THREAD

**Issue by kenperkins** [jrperritt/rack#164]
If I run:

```
/data/src/rack [contributing] $ rack servers instance create --name foo
PROPERTYVALUE
error	One and only one of ImageRef and ImageName must be provided.
```

We don't use `ImageRef` and `ImageName` as flags, so it's confusing for an end user to fix their usage of `rack servers instance create`

**Comment by kenperkins** [comment]
We should fix all of the cases where these values that are returned from Gophercloud differ from the usage in `rack`

**Comment by kenperkins** [comment]
Must do for public beta, as this is raw feedback from the cloud API, as opposed to the `rack` interface. Effectively a leaky abstraction.

**Comment by kenperkins** [comment]
We expect to not have the PR merged into Gophercloud sufficient to get this in for Public Beta. We'll add to the release notes in #224

**Comment by jrperritt** [comment]
Hmm, after thinking about this: the PR is in rackspace/gophercloud and unmerged, but _this_ repo is actually using it's own internal version of Gophercloud. So we _could_ put (and I'm leaning toward putting) that PR in `rack`'s verndored Gophercloud code and use it from there.

**Comment by jrperritt** [comment]
I think I've addressed this issue. If any specific errors are found that aren't addressed, they can be filed as bugs.
