### ISSUE TITLE
Suppress Header

### ISSUE THREAD

**Issue by rgbkrk** [jrperritt/rack#167]
Add a flag to suppress the header.

Current choices we've talked at length about

* ~~`-q` - Docker uses it to only report back IDs (which are UUIDs), wget and curl use it to suppress *all* output~~ We decided against this one since quiet doesn't make sense.
* `--no-headers` - on the GNU version of `ps`, this suppresses headers

We should pick one to make a unified approach to the piping.

**Comment by jrperritt** [comment]
I prefer `--no-headers` (or `--no-header`). `-q`, though terse, is really uninformative.

**Comment by kenperkins** [comment]
Agree on `--no-header` or `--no-headers`.

`--no-headers` implies there are multiple discrete header rows, so that's a bit odd.

**Comment by kenperkins** [comment]
Let's do `--no-header`.
