### ISSUE TITLE
Document that Rack configure does not work in Windows Powershell ISE

### ISSUE THREAD

**Issue by hdansou** [jrperritt/rack#169]
When I run ```rack configure``` from a powershell prompt, it displays the command message but the cursor blinks continuously  without allowing a keyboard insert.

![rack-configure](https://cloud.githubusercontent.com/assets/536716/8517126/bcd5b616-2382-11e5-8ab6-91a5856797b5.jpg)

**Comment by jrperritt** [comment]
@hdansou Hmm, well that's not good. This is what I get on Windows Server 2012 Powershell:
```
PS C:\Users\Administrator\Downloads> .\rack.exe configure

This interactive session will walk you through creating
a profile in your configuration file. You may fill in all or none of the
values.

Rackspace Username:
```

Do you have the latest binary? The windows version of `rack configure` was having some issues a week or so ago but have since been resolved. Also, which Windows version are you running?

**Comment by hdansou** [comment]
I am running Windows Server 2012 R2 with powershell version 5. 
 I have used the binary from https://ba7db30ac3f206168dbb-7f12cbe7f0a328a153fa25953cbec5f2.ssl.cf5.rackcdn.com/Windows/amd64/rack.exe. It does not have a version number, so I can't tell if it is the latest or not.

I suggest creating github release/tag for each new version so we can download from there.

**Comment by jrperritt** [comment]
Yes, we are planning on switching to a naming convention that uses the commit hash. Currently the binaries in that CDN container are the latest builds.

It looks like I'm testing on PowerShell version 4. I'll see if I can test on version 5.

**Comment by hdansou** [comment]
The issue is with Powershell ISE(IDE). I tried it on just powershell and it worked.
![rackspace-cli-2015-07-06 15-04-45](https://cloud.githubusercontent.com/assets/536716/8530723/9fc0ab8a-23f0-11e5-9567-4270950a09d7.jpg)

**Comment by jrperritt** [comment]
Hmm! OK, good to know. 

I'd not heard of PowerShell ISE; Is it more popular for Windows users than PowerShell? It indeed looks like PowerShell ISE will not work with `rack configure`, or any other command that asks for user input if the content on this page is still valid: http://blogs.msdn.com/b/powershell/archive/2009/02/04/console-application-non-support-in-the-ise.aspx

We can specify in the docs the necessitation for Windows users to use PowerShell.

**Comment by hdansou** [comment]
That is the issue. We should document like you said. it should be use on powershell.exe and not powershell_ise.exe, otherwise we end up with the weird command line issues.

**Comment by kenperkins** [comment]
We're going to document that Powershell ISE has issues with interactive prompts.
