### ISSUE TITLE
Semantics

### ISSUE THREAD

**Issue by rgbkrk** [jrperritt/rack#17]
This is pretty awesome. There are some issues I'm taking with the current verbage when reading left to right.

## Compute reads as a verb

```
rack compute flavors
```

Read directly, I see `compute` as a verb which is a cognitive disconnect for me.

![screenshot 2015-06-07 19 35 06](https://cloud.githubusercontent.com/assets/836375/8026815/fd57f7cc-0d4c-11e5-88cb-0a708e854e75.png)

For non-server sections, it would flow as a resource with `server` at the front:

```
rack server flavors list
rack server images list
rack server keypairs list
```

I'll come back to this. The weird thing is that Rackspace mycloud lists "Servers" under "Servers".

## Pipable outputs

It's really great to see that json dump is available. Some kind of planar tab delimited format would be great as well, so that I can chain it together with other *nix commands (or even PowerShell). `--plain`?

**Comment by jnoller** [comment]
We could do rack servers vs compute - but not rack-servers

**Comment by rgbkrk** [comment]
What should we do for listing running servers? How's

```
rack server instances
```

**Comment by jnoller** [comment]
rack servers instance list ? List is one action you take on servers.

**Comment by rgbkrk** [comment]
Updated text above, but yes if `list` is not implied then append it (as currently implemented).

**Comment by jnoller** [comment]
I think explicit actions are better than implicit; being of by an "s" on a command is surprising 🎂

**Comment by rgbkrk** [comment]
One of the paradigms I'm looking to go after includes:

```
rack servers instance list --name 'tmp22*' -q  | rack servers instance delete
```

Which, it's worth noting that @jrperritt already did an excellent job of handling filters:

```
$ rack compute servers list --name='tmp25.*'
+--------------------------------------+----------------------+--------+----------------+---------------+--------------------------------------+-----------------+
|                  ID                  |         NAME         | STATUS |  PUBLIC IPV4   | PRIVATE IPV4  |                IMAGE                 |     FLAVOR      |
+--------------------------------------+----------------------+--------+----------------+---------------+--------------------------------------+-----------------+
| e57f05bd-f1c6-4145-acec-f3998cc2167c | tmp25-user.tmpnb.org | ACTIVE | 23.253.157.223 | 10.184.5.126  | dc6799b8-c6e4-4446-8ec8-4628de7d77c5 | onmetal-memory1 |
| cac928b7-fb62-4b87-a5e6-92d176e76fb7 | tmp25.tmpnb.org      | ACTIVE | 162.209.124.30 | 10.223.242.77 | 6f29d6a6-9972-4ae0-aa80-040fa2d6a9cf | performance2-15 |
+--------------------------------------+----------------------+--------+----------------+---------------+--------------------------------------+-----------------+
```

One has to be careful in noting that it's a full regex here (I used `name=tmp25*` at first, got back way too much).

After that, trimming it to the ones I want is a chain of figuring out the way this is laid out:

```
$ rack compute servers list --name='tmp25.*' | cut -d'|' -f2
+--------------------------------------+----------------------+--------+----------------+---------------+--------------------------------------+-----------------+
                  ID
+--------------------------------------+----------------------+--------+----------------+---------------+--------------------------------------+-----------------+
 e57f05bd-f1c6-4145-acec-f3998cc2167c
 cac928b7-fb62-4b87-a5e6-92d176e76fb7
+--------------------------------------+----------------------+--------+----------------+---------------+--------------------------------------+-----------------+
```

```
$ rack compute servers list --name='tmp25.*' | cut -d'|' -f2 | grep -e '[0-9a-fA-f]\{8\}'
 e57f05bd-f1c6-4145-acec-f3998cc2167c
 cac928b7-fb62-4b87-a5e6-92d176e76fb7
$ rack compute servers list --name='tmp25.*' | cut -d'|' -f2 | grep -e '[0-9a-fA-f]\{8\}' | sed 's/ //g'e57f05bd-f1c6-4145-acec-f3998cc2167c
cac928b7-fb62-4b87-a5e6-92d176e76fb7
```

```
$ rack compute servers list --name='tmp25.*' | cut -d'|' -f2 | grep -e '[0-9a-fA-f]\{8\}' | sed 's/ //g' | rack compute servers delete
Missing flag: One of either --id or --name must be provided.
Usage: rackcli compute servers delete [--id <serverID> | --name <serverName>] [optional flags]
```

Hoping for a default of image IDs being sane:

```
$ rack compute servers delete $( rack compute servers list --name='tmp25.*' | cut -d'|' -f2 | grep -e '[0-9a-fA-f]\{8\}' | sed 's/ //g' )
Expected 0 args but got 2
Usage: rackcli compute servers delete [--id <serverID> | --name <serverName>] [optional flags]
```

Final result
```
$ for srv in `rack compute servers list --name='tmp25.*' | cut -d'|' -f2 | grep -e '[0-9a-fA-f]\{8\}' | sed 's/ //g'`; do rack compute servers delete --id $srv; done
```

The other option would have been to use the JSON response, ripping the fields I needed out (or building that all with `sed`).

What a long winded way of me chiming in to say that I think tables should just be plain (think `docker ps` or `docker images`) and that things like delete or get can take IDs by default unless specified otherwise. I'll draft a PR with a different case to think about.

**Comment by jrperritt** [comment]
Having plain tables is a good idea, may be preferable at times, and wouldn't be much of a deviation from the current tabular format. I was going to refactor the commonalities among tables anyhow (see #1 ).

I'm going to have to push back on changing the syntax verbiage and on not using flags for specifying both ID and name.

My design priorities are as follows:
1. Correctness: The commands and flags work as expected
2. Consistency: The commands and flags are consistent across services
3. Completeness: The CLI supports all services equally.
4. Terseness: The CLI commands and flags are only as long/complicated as needed to satisfy 1 through 3 above.

Using the `rack <service> <subservice> <action>` format will be beneficial down the road for consistency and clarity. I understand that leaving out the `<service>` argument would be unambiguous for the `compute`, `networking`, and `block storage` services, but there will be other services that are not as friendly (`cdn`, `load balancers`). In addition, with bash-completion enabled, having one additional argument (namely, `<service>`) should not be a burden for users.

I'm not sure I understand the appeal of allowing ID as an argument, say for `rack compute servers get`, but then forcing the use of a flag to use a name as the argument. Why not have users explicitly say which they're providing with `--id` and `--name` flags?

**Comment by rgbkrk** [comment]
I don't think I said to leave out the service, but to assume some context about listing by default. That was primarily a though on not liking the name `compute` as the service. The service name is servers to me (compute is what nova calls it, Rackspace calls them cloud servers) while a running one is an instance.

> I'm not sure I understand the appeal of allowing ID as an argument, say for rack compute servers get, but then forcing the use of a flag to use a name as the argument. Why not have users explicitly say which they're providing with --id and --name flags?

Mostly to allow for batches of ids, to do multiple operations in one flow.

From Docker:

```
docker rm -fv $( docker ps -aq )
```

To here:

```
rack servers instance list --name 'tmp22*' -q  | rack servers instance delete
```

I ask for that because I commonly do that with a series of Rube Goldberg *nix commands against nova. Then I realize that the control panel is easier at expressing things and I just do it there. I don't want to have to copy and paste IDs if I don't have to. Same goes for rebooting a collection of servers, etc.

**Comment by jnoller** [comment]
> I don't think I said to leave out the service, but to assume some context about listing by default. That was primarily a though on not liking the name compute as the service. The service name is servers to me (compute is what nova calls it, Rackspace calls them cloud servers) while a running one is an instance.
> 
Good catch- for the cli we need to be using the Rackspace names, not the openstack name (eg files, servers, etc)

**Comment by jrperritt** [comment]
http://docs.rackspace.com/

> The service name is servers to me (compute is what nova calls it, Rackspace calls them cloud servers)

Everyone who goes to that page is greeted with a large `Compute Services` header.

**Comment by jnoller** [comment]
The services header is misleading collection of services you use; the actual service is servers

Jesse

**Comment by jrperritt** [comment]
> I don't think I said to leave out the service, but to assume some context about listing by default.

Oh, OK, my mistake.

> The services header is misleading collection of services you use; the actual service is servers

OK, I'll make the change.

**Comment by rgbkrk** [comment]
I'd say this is largely addressed. Closing.
