### ISSUE TITLE
deleting full containers gives html back

### ISSUE THREAD

**Issue by jamiehannaford** [jrperritt/rack#174]
```bash
$ rack files container delete --name racktest
error	<html><h1>Conflict</h1><p>There was a conflict when trying to complete your request.</p></html>
```

we should probably delete the contents of the container by default, since this is probably what users want. or alternatively, we could keep it as it is, but add an `--empty` flag that allows users to easily override.

**Comment by jrperritt** [comment]
The returning-HTML bit is related to #164 . That is the error coming from Rackspace. As for the feature request, see my comment on #175

**Comment by jamiehannaford** [comment]
happy to close for #164
