### ISSUE TITLE
feature request: emptying containers

### ISSUE THREAD

**Issue by jamiehannaford** [jrperritt/rack#175]
related to #174, it would be really cool if I could empty all the contents of a container as a separate command like so:

```bash
rack files container empty --name foo
```

**Comment by jrperritt** [comment]
Are you wanting this functionality in general or are you wanting it as a separate command? Currently you can do this with the `purge` flag: https://github.com/jrperritt/rack/blob/master/commands/filescommands/containercommands/delete.go#L33

**Comment by kenperkins** [comment]
`--purge` deletes the container and all files, where as maybe `--empty` keeps the container. I'm not sure we need empty as you could easily do `rack files container delete --purge --container my-container && rack files container create --name my-container`

**Comment by jamiehannaford** [comment]
well, there's two things I'd say to that:

1. the above command will not retain the metadata of the old container if anything is set
2. it's an extra 51 chars for the user to write (and remember). IMO a good tool should make it as easy as possible to do expected things

deleting the contents of a container is a fairly common use case -- I use it all the time -- so I think a separate `empty` command would be quite useful. the `--purge` flag for the delete command could reuse empty.

**Comment by kenperkins** [comment]
Agree that a better UX is always preferred. Was just saying it was somewhat doable now.

**Comment by kenperkins** [comment]
We're doing this for public beta.
