### ISSUE TITLE
Download semantics for Files

### ISSUE THREAD

**Issue by kenperkins** [jrperritt/rack#18]
Currently, Swift is the only API that when given a GET request, I.e. `/mycontainer/myfile.txt` it returns the *contents* of the file, not the metadata.

Should we follow this discrepancy in the CLI? or should we provide consistency.

For example:

`rack files object get --container mycontainer --file myfile.txt` could return the metadata and
`rack files object download --container mycontainer --file myfile.txt` would then return the contents?

Pros: Consistent calling convention across all services.
Cons: Most likely use of files will involve getting the file, not the metadata, leading to more typing in the default case.

Thoughts?

**Comment by kenperkins** [comment]
As I think about this with @rgbkrk I feel like `--download` is a better option. It will never surprise you when the option is explicit.

**Comment by rgbkrk** [comment]
Do we assume stdout or a download in these cases?

I could see myself using

```
rack files my-container log1.txt --download | grep "500 Internal Server Error"
```

**Comment by jrperritt** [comment]
The problem I'm having with that syntax is that it's not consistent with the other services. Currently, we have a `rack <service> <subservice> <action> <flags>` format.
To stay consistent, It'd need to be something like:
`rack files object download --container <containerName> --object <objectName>`

**Comment by kenperkins** [comment]
I like it from a consistency standpoint (@jrperrit) but it does add a significant amount of typing. Perhaps it's worth it?

**Comment by rgbkrk** [comment]
There's not really a subservice on cloudfiles is there? Also, `object` confuses, for me, the access of a single object vs a container. This would come out as:

```
rack files object list --container <containerName>
```

**Comment by rgbkrk** [comment]
Would `rack files container list` make more sense?

**Comment by jrperritt** [comment]
Closing for now. This has been implemented. Comment and/or re-open to to continue discussion.
