### ISSUE TITLE
Set default output in the config file

### ISSUE THREAD

**Issue by hdansou** [jrperritt/rack#182]
It will be great to have a preference setting on the config file ~\.rack\config
```
[preference]
output = json
default_profile = third_profile
```

For example, on windows, it is best to set the `--output=json` which we can convert from json to .Net object and take advantage of Powershell's .Net object manipulation and command line intellisense. 
This allows us to not upload third party linux tools like grep, tail on windows computers to effectively use the CLI.

**Comment by kenperkins** [comment]
We've talked about this in #63.

**Comment by kenperkins** [comment]
Closing this to move discussion to #63.
