### ISSUE TITLE
Not able to get the -userdata option to work

### ISSUE THREAD

**Issue by letterj** [jrperritt/rack#194]
I've tried several different ways to get any type of cloud-config.yml or cloud-config.sh file to work and nothing seems to happen.  Nothing in either the /var/log/cloud-init.log or /var/log/cloud-init-output.log files.  Do you have a working example or test.

**Comment by letterj** [comment]
It would also be good to have a "File Not Found" message displayed if the file does not exist.

**Comment by jrperritt** [comment]
The latter (:point_up:) we will definitely have. The former ( :point_up: :point_up: ) I'll look into. I'll be writing acceptance tests all of next week; I'll start with `instance create` and address both of those concerns on Monday.

**Comment by letterj** [comment]
Thanks for your response.  Do you actually have a working example of the "userdata" parameter.  I've looked at everything I could find in RAX documentation and couldn't get every example I found to work.   But I'm still working through any example I can find.

**Comment by kenperkins** [comment]
We need to add a solid repo for this issue.

**Comment by letterj** [comment]
I was able to get an example of the userdata option working with the following cloud-config.txt file and supernova command and options.   It seems the option "--config-drive=true" is required for it to work.  Currently, that option is not available in the "rack" client.  

cloud-config.txt
<pre>
#cloud-config

# Update apt database on first boot
package_update: true

# Install new package
packages:

 - vim

# Setup vim as the default editor
runcmd:

 - update-alternatives --set editor /usr/bin/vim.basic
</pre>

supernova command and options
<pre>
supernova <profile> boot --config-drive=true \
  --flavor performance1-1 \
  --image edd916d6-8136-4a24-afa5-99b044e38f75 
  --user-data cloud-config.txt  
  --key-name <ssh-key> userdatatest00
</pre>

**Comment by jrperritt** [comment]
Ah, good to know. Thanking you for trouble-shooting it; I'll add a `config-drive` flag tomorrow.

**Comment by jrperritt** [comment]
#208 sets the `config-drive` for you if you provide the `user-data` flag. I've confirmed this works with the following user-data script (saved to ~/user-data.txt):

```
#cloud-config
users:
  - name: rack-created-user
    ssh-authorized-keys:
      - [PASTE YOUR PUBLIC SSH KEY HERE]
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
```

Create a server:
```
rack servers instance create --name testRackUserData --image-id 587ee022-8dfe-43e8-ad8b-b4efb1fc1d71 --flavor-id 3 --user-data ~/userdata.txt
```

and then when it's available, SSH to the server:
```
ssh rack-created-user@[PASTE THE SERVERS PUBLIC IP ADDRESS HERE]
