### ISSUE TITLE
different authentication methods

### ISSUE THREAD

**Issue by jrperritt** [jrperritt/rack#2]
Methods to support:
- [x] environment variables
- [ ] command-line parameters
- [ ] config/ini file
- [ ] keyring

Also, token caching:
- [ ] caching the auth token to prevent re-authing for every command

**Comment by jnoller** [comment]
"gopkg.in/ini.v1" for INI config file format

**Comment by jrperritt** [comment]
:+1: Agreed

**Comment by jrperritt** [comment]
@rgbkrk Are you still planning to work on this?

**Comment by rgbkrk** [comment]
The keyring bits need support upstream, unless we only want to support OS X and Linux out of the box. I think the env and cli params are fine for now.

**Comment by jrperritt** [comment]
*and ini/config

I agree.

**Comment by jrperritt** [comment]
I'm gonna take this one while @rgbkrk 's working on table output.

**Comment by jrperritt** [comment]
closed by #59

**Comment by jrperritt** [comment]
keyring on windows (vault) may not make it into `mvp`.

**Comment by rgbkrk** [comment]
Yeah, I think it's sensible that our mvp would only have keyring support on *nix variants.
