### ISSUE TITLE
Enable path auto-completion on appropriate flags

### ISSUE THREAD

**Issue by kenperkins** [jrperritt/rack#207]
as of #205 we will no longer error when auto-complete is invoked during a flag. We should still support auto-completion when typing in a path in a flag, for example:

`rack files object upload --container foo --file ~/my-file<tab>`.

**Comment by jrperritt** [comment]
Fixed here: https://github.com/jrperritt/rack/commit/a59c37893c715c5cd0ab8e296c3897c4e6f0dd4a
