### ISSUE TITLE
Make environment variables more in line with existing tools

### ISSUE THREAD

**Issue by eljrax** [jrperritt/rack#210]
Any chance it can be considered to change the specified environment variables to match those of many existing tools in the style of OS_REGION_NAME as in nova, turbolift and so on. 
I suspect many people already have these set and are used to working with them.

**Comment by jnoller** [comment]
@eljrax The issue with the OS_ prefix used is the spread of those variables - it's actually one of the worst user experience issues with the various clients, and managing them is basically a nightmare if you're floating between products. 

We prefer *not* to adapt to those variables and instead expose only a limited, well identified set to customers. We get constant support issues / complains about the OS_* vars, managing them, managing environments - cleaning this up and making it clear this is a rackspace cloud userspace is critical as this is meant for rackspace customers.

**Comment by eljrax** [comment]
I guess I've become 'institutionalised' and used to working that way.

Fair point, thanks for considering it! Closing issue.
