### ISSUE TITLE
name and id flags

### ISSUE THREAD

**Issue by jrperritt** [jrperritt/rack#3]
We may want to consider `name` and `id` flags for most of the commands (`get`, `update`, `delete`) so that users can provide, for example, a server name rather than a server ID. I'm not sure how people feel about flags vs arguments. With arguments, we'd have something like:

```rackcli compute servers get <serverID>```

and with flags it'd look like:

```rackcli compute servers get --id <serverID>``` 
or 
```rackcli compute servers get --name <serverName>```

Another option is to combine the 2 and assume that if an argument is provided that it's an ID. If not provided, look for flags. I know that using arguments for IDs is customary, but I suspect people more often than not would prefer to provide a name.

**Comment by jnoller** [comment]
I think I'm a fan of: `rackcli compute [servers | instances] [create | get] <id or name>` vs. the flag - flags would be --region or in the case of create, other arguments. Thoughts? @rgbkrk

**Comment by jrperritt** [comment]
OK. The only problem I see with not using flags is determining whether or not the user has given a name or an ID as the argument.

**Comment by jrperritt** [comment]
Closing for now in favor of `--name` and `--id` flags. If anyone wants to reopen the discussion, feel free to reopen the issue.

**Comment by rgbkrk** [comment]
I'm in favor of the `--`less version as well, though I think compute I'm less opinionated as compared to object storage (where sematics should match Linux command line counterparts).

**Comment by jrperritt** [comment]
Consistency is the most important thing to me. Without the flags, we can't reliably determine whether an argument is an ID or a name across all services. In addition, the semantics of all services should be identical, and I think I'd prefer to err on the side of explicitness (such as `list` instead of `ls`).
