### ISSUE TITLE
Typo suggestions

### ISSUE THREAD

**Issue by rgbkrk** [jrperritt/rack#41]
Not all systems have bash (e.g. Windows) and not everyone uses bash completion. One helpful thing a lot of client bindings do is provide suggestions. Example for us:

```
$ rack server instance list
rack: 'server' is not a rack command. Did you mean "rack servers instance list"?
```

**Comment by kenperkins** [comment]
+1 on this. I constantly forget and pluralize the resource.

Here's what git does:

```
/data/src/rack [master] $ git stitus
git: 'stitus' is not a git command. See 'git --help'.

Did you mean this?
	status
```

**Comment by kenperkins** [comment]
That said, I think we can figure out a solution here post MVP.

**Comment by kenperkins** [comment]
We have this for commands, but not for flags. I think that's good enough to call this closed.
