### ISSUE TITLE
buffering output

### ISSUE THREAD

**Issue by jnoller** [jrperritt/rack#49]
Right now in order to build the output we buffer all of the response payload in memory before outputting to the user. This means for command chains or just lots of output the memory usage could get ghastly for end users and potentially trigger the oom killer on the CLI process itself (or fall into swap). We should consider using a streaming interface for output when possible.

**Comment by jrperritt** [comment]
We can (and should) definitely do this for file download. Beyond that, are there other responses that would need buffering?

**Comment by jnoller** [comment]
AFAIK glance operations might (image upload). Be careful with file download buffering too - if you do a download of a 5gb file and you're buffering it instead of streaming it to disk, you're going to run out of ram and have a bad day. Even if you're downloading to a temporary fd and then moving it to the target you're safer than keeping it in memory.

**Comment by jrperritt** [comment]
True. Glance operations still need to be added to Gophercloud. We can stream to file with the current Gophercloud file download implementation.

**Comment by jrperritt** [comment]
I think we can close this. Currently we're streaming file uploads and downloads. If this changes or isn't working, we'll re-open.
