### ISSUE TITLE
cloud block storage commands

### ISSUE THREAD

**Issue by jrperritt** [jrperritt/rack#5]
volumes:
- [ ] create
- [ ] get
- [ ] update
- [ ] delete

snapshots:
- [ ] create
- [ ] get
- [ ] update
- [ ] delete

**Comment by meteorfox** [comment]
Also, how would a user boot an instance from a CBS volume?

There are 2 ways supported by Rackspace:
* (2-steps approach) Prepare a boot volume with an image, then map it as block device to the instance
* Specify the all-in-one block-device flag, that will do all the steps in a single command
  * Cloud Control uses this option

Probably the command `instances create` will need to take a new flag for the disk

[Docs](http://www.rackspace.com/knowledge_center/article/boot-a-server-from-a-cloud-block-storage-volume)
