### ISSUE TITLE
Do not use spaces in JSON keys

### ISSUE THREAD

**Issue by everett-toews** [jrperritt/rack#55]
I think we should seriously consider not using spaces in JSON keys. When people are parsing/selecting on JSON keys, any spaces in the key can require annoying escaping. It becomes a papercut.

For example, if you were to try to get the private IP address of 2 servers that are named the same ("rum") using jq.

```
$ rack --json servers instance list | jq -r '.[] | select(.Name == "rum").Private IPv4'
error: syntax error, unexpected IDENT, expecting $end
.[] | select(.Name == "rum").Private IPv4                                     1 compile error

$ rack --json servers instance list | jq -r '.[] | select(.Name == "rum").Private\ IPv4'
error: syntax error, unexpected INVALID_CHARACTER, expecting $end
.[] | select(.Name == "rum").Private\ IPv4                                    1 compile error
```

I'm sure there's some escaping I can do to fix this or use some other tool that maybe handles spaces in keys better but it feels like there will always be some amount of having to work around spaces in key names.

**Comment by rgbkrk** [comment]
I find spaces more legible to read within output as a human but find it hard to use with space delimited tabular output (note: we're using plain tabs). I won't vouch for either direction, but here's how I'd get that field with `jq`:

```
$ rack --json servers instance list | jq -r '.[] | select(.Name == "nature.tmpnb.org")["Public IPv4"]'
104.130.19.7
```

My favorite tool is `json` from `npm`. This is how I would use it in this case:

```
$ rack --json servers instance list | json -a "Public IPv4" -c 'this.Name === "nature.tmpnb.org"'
104.130.19.7
```

**Comment by jnoller** [comment]
Pretty print to people: good. Command chaining as you are doing should be a flag to disable / advanced use case

**Comment by everett-toews** [comment]
No need to add another flag (more complexity) for this. I'd be fine with leaving it as is but making sure we document an example of working with a space in a JSON key over in #54.

**Comment by minecraftchest1** [comment]
what about camelCase?
