### ISSUE TITLE
PowerShell command completion

### ISSUE THREAD

**Issue by jrperritt** [jrperritt/rack#56]
I don't know the effort level involved in this, but it's probably worth looking into.

**Comment by hdansou** [comment]
It may require writing a Powershell wrapper for the rackspace cli. 
The other option is to investigate https://github.com/lzybkr/TabExpansionPlusPlus which I have not used yet, but it seems like creating an Argument Completers file like https://github.com/lzybkr/TabExpansionPlusPlus/blob/master/RobocopyExe.ArgumentCompleters.ps1 will work.

**Comment by jrperritt** [comment]
True; I stumbled upon that repo during research for this issue. Though I've approximately zero experience developing for Windows environments, based on what I've read so far, it sounds like we should be able to provide custom completion options to the `global:TabExpansion2` function. The CLI library we're using returns the completion options given a partial command, so we _hopefully_ we can just pass that array to the `$options` parameter of the `global:TabExpansion2` function.

Alternatively, we could create a hashmap of options for all the `rack` commands and subcommands to pass to the `TabExpansion` function. For that, we'd probably want to make a template for the custom tab-completion function, and then compile it when `go build` runs.

**Comment by kenperkins** [comment]
We're hoping to get this done for public beta.

**Comment by kenperkins** [comment]
I would be ok living without this for our first "public" release.
