### ISSUE TITLE
Should contradictory flags work or error?

### ISSUE THREAD

**Issue by kenperkins** [jrperritt/rack#61]
Given the following call:

`rack servers instances delete --id 12345 --name foo`

What should happen?

Options

1. Delete based on provided `id`
2. Delete based on provided `name`
3. Delete based on provided `name` and `id`
4. Error with a useful error message

Thoughts?

**Comment by kenperkins** [comment]
This also applies if we decouple `public-key` and `file` as flags on `servers keys create` or `contents` and `file` for `files object create`.

**Comment by jnoller** [comment]
error

**Comment by jrperritt** [comment]
Currently, it performs logic based on `1`. I like option `4`.

**Comment by rgbkrk** [comment]
![We should error](http://media.giphy.com/media/GMekhaa82P63C/giphy-tumblr.gif)

**Comment by kenperkins** [comment]
+1 on error (`4`)
