### ISSUE TITLE
flag naming convention

### ISSUE THREAD

**Issue by jrperritt** [jrperritt/rack#62]
Currently the flags are named like Go varaibles: `flavorID`, `publicKey`. We should probably move to a more conventional naming method like kebab-case: `flavor-id`, `public-key`.

**Comment by rgbkrk** [comment]
:+1: for kebab case. The Go casing was driving me mad on the command line, but I left that one :fire: alone.

**Comment by kenperkins** [comment]
I've always biased to kebab casing. Admittedly subjective.

**Comment by rgbkrk** [comment]
Objectively (but with some hand wavey regexes), we can look at the options specific in man pages to see which do lowercase, digits, and dashes between.

```
/usr/local/share/man$ grep -R Item . | grep '[0-9a-z]\+\(-\+[0-9a-z]\+\)*"$' | wc -l
    6404
/usr/local/share/man$ grep -R Item . | wc -l
    7095
/usr/local/share/man$ python3 -c "print(6404/7095)"
0.9026074700493305
```

That's a little over 90% of all flags from all the man pages on my system. I'd say it's fair to say we're not breaking norms by switching to kebab-case.

**Comment by kenperkins** [comment]
:+1: to `kebab-case`.

**Comment by jrperritt** [comment]
I'll start converting the `servers` flags now.
