### ISSUE TITLE
Global configuration

### ISSUE THREAD

**Issue by kenperkins** [jrperritt/rack#63]
Should we be able to specify global defaults in the config?

```ini
[Global]
no-cache=true
output=json
debug=true

[Default]
region=iad
username=asdf
api-key=asdf1234

[Test]
region=iad
username=asdf
api-key=asdf1234
output=table
```

A couple of other thoughts? Should there be a default profile? or should `[Global]` be able to be overriden?

**Comment by kenperkins** [comment]
Another possibility:

```ini
username=asdf
api-key=asdf1234
no-cache=true
format=json

[Test]
format=table
debug=true
```

**Comment by rgbkrk** [comment]
I definitely like that. Sensible defaults for that given user.

**Comment by kenperkins** [comment]
You like which?

**Comment by rgbkrk** [comment]
I guess I mean `#1`, looking over it. I like the `format=json` and `debug=true` as well.

**Comment by kenperkins** [comment]
I wonder why we'd need both `[Default]` and `[Global]`. They seem synonymous.

**Comment by rgbkrk** [comment]
I think the intention was that `[Default]` is your default user, region, api key pairing.

Your introduction of `[Global]` would mean options to me.

**Comment by kenperkins** [comment]
Updated my comments to use the example of `output=json` as we had discussed format being ambiguous.

**Comment by kenperkins** [comment]
Updating this to reflect the current state of the union:

```ini
username = foobar
apikey = 123456789
region = IAD

[test]
username = foobar-test
apikey = 123456789a
```

The question now is whether we allow other values to be set via the configuration file. I think we should.

**Comment by kenperkins** [comment]
Currently, the top of the `config` file are globals, or `Default`, as they are not defined by an INI file `Section`, (defined as `[SectionName]`). Our current behavior does not allow a named profile to override the globals, but rather must be complete.

Example:
```ini
username = foobar
apikey = 123456789
region = IAD

[test]
username = foobar-test
apikey = 123456789a
```

In this example, using `rack servers instance list --profile test` would fail, as `test` does not define a region. To support globals, I propose we should allow inheriting from the global, or default profile, when using any other profile. Here is an example:

```ini
username = foobar
apikey = 123456789
region = IAD
output = json

[test]
username = foobar-test
apikey = 123456789a
```

With same call, `rack servers instance list --profile test` I would expect to override `username` and `apiKey` with values from the `test` section, and inherit `region` and `output` from the default.

Thoughts?
