### ISSUE TITLE
ImageName flag in servers/create ambiguity

### ISSUE THREAD

**Issue by rtgoodwin** [jrperritt/rack#65]
Issue to be researched: To date, it has been best practice with Cloud Servers and Cloud Images to not have customers building images by specifying (or fuzzy matching) the image name. Often the images are changed or updated silently, and the name stays the same, which has led to customer confusion and breakage in more than a couple of instances. This might need to be deprecated; should follow up with Ari Liberman, Amanda Clark on Servers/Images team when builds are more widely distributed.

**Comment by carolynvs** [comment]
What is the best practice? I had thought that hard coding the id in scripts was discouraged and that looking up by name first was the way to go...

**Comment by rtgoodwin** [comment]
@carolynvs This rabbit hole goes pretty deep :) We (by which I mean when I was the Servers/Images PM) DID generally discourage hard coding ID's in scripts IF your desire is always to have the latest image regardless of what changes/fixes/iterations we've made to it. 

But the reality is that a UUID, being something that is fixed and will never go away (we don't delete old image UUIDs, just hide them from public listing), is what you want if you want an absolute guarantee that nothing has changed in your source image. (In fact Glance essentially enforces that all images, once created, are immutable). 

So, then you ask, what is the way to do it if you don't specify the name? We had generally recommended either using the ID and auditing time to time, OR using additional metadata on the image to determine the distro, the version, and the creation date (or some other unique combination). The reality is that Glance doesn't have a great way to make this work out of the box, it requires client side caching, customized parsing, or just plain old user involvement, so I can't claim to offer a specific solution, only some guidance on things that have been proven to cause user issue in the past. I will defer to those teams for the UX they want for their products. Just didn't want to lose track of the concern. :)

**Comment by carolynvs** [comment]
Thanks @rtgoodwin for the explanation!

**Comment by kenperkins** [comment]
This is a followup for @rtgoodwin on communicating best practice here, but this doesn't appear to have any direct code ramification on `rack`.

**Comment by rtgoodwin** [comment]
Bounced to Ari and Amanda for their feedback.

**Comment by rtgoodwin** [comment]
Response from Images team: 

"It really depends on what the customer is trying to do.  If they always want to be guaranteed the exact same image then they should build via UUID or use a snapshot.  Of course, this gives them a static image that will not be updated or patched.  If they always want the latest most up-to-date version of their OS they can use the name, but they should be aware that the point release could change out from under them if they’re using RHEL/Cent, or their code could break if we remove their image from the base image list (e.g., removing Ubuntu 15.04 when 15.10 comes out).  The best approach varies depending on what OS you’re using. "

So, we'll work it in our docs in conjunction with the Images team.

**Comment by kenperkins** [comment]
Lets add a note to the docs saying that depending on the name for an image may result in unexpected changes. Images often are updated with security patches that may have the same `Name`.
