### ISSUE TITLE
Output current config/options during calls?

### ISSUE THREAD

**Issue by kenperkins** [jrperritt/rack#73]
Proposal: display some relevant information about your request:

```bash
$ rack --region syd servers instance list
Profile: Default        Username: kpraxtest       Region: SYD
ID	Name	Status	Public IPv4	Private IPv4	Image	Flavor
```

I've found when using lots of profiles and overriding values like `region` that it gets confusing looking at the output without some feedback of which account I'm actually using.

Maybe this would be best as a config option that could be globally set?

Thoughts?

**Comment by rtgoodwin** [comment]
+1 here. Reinforces the patterns and learnings around profiles and regions.

**Comment by rgbkrk** [comment]
I like showing some of that request information, since it may be hidden. Not sure how to format that well, relative to the rest of the table (sticking in JSON is no problem).

**Comment by kenperkins** [comment]
My motivation was that not all profile names will coincide with rax api username. So being able to optionally output that info might be very useful.

**Comment by jrperritt** [comment]
I think this information should be printed if `--log info` is provided (when logging is implemented).

**Comment by kenperkins** [comment]
+1 on using `--log info` to show current user information.

**Comment by rgbkrk** [comment]
Makes sense that it would get included on logging at higher levels. :+1:

**Comment by jrperritt** [comment]
This is getting rolled into the PR for #40
