### ISSUE TITLE
Errors should exit with non zero exit code

### ISSUE THREAD

**Issue by kenperkins** [jrperritt/rack#74]
For example, if I run this command with invalid credentials, it won't show anything, and will run grep because the previous command exited with `0`.

```bash
/data/src/rack [design] $ rack servers image list | grep ubuntu

```

**Comment by jrperritt** [comment]
Hmm. What would be the expected behavior? It's true that we should return a non-zero exit code on error, but I think in your case it would run grep either way (since you'd be getting back an error message).

**Comment by kenperkins** [comment]
I incorrectly assumed that non-zero exit would fail to execute after the pipe.

**Comment by jrperritt** [comment]
For that, we'd have to exit before anything was printed. We _could_ do that, but the user wouldn't get back an error message.

**Comment by kenperkins** [comment]
Lets just make sure we return non-zero for error cases and leave it at that.

**Comment by rgbkrk** [comment]
What makes us have to exit before printing? All manner of tools will print on stderr and exit with a return code.

**Comment by jrperritt** [comment]
> For that, we'd have to exit before anything was printed.

*printed to stdout

**Comment by rgbkrk** [comment]
Nevermind me, it looks like you handled it right in #77 + #76
