### ISSUE TITLE
Improve the output message when no config/flags/env variables specified 

### ISSUE THREAD

**Issue by rtgoodwin** [jrperritt/rack#84]
Currently if I don't use a profile or export env variables, we get a generic error:

"PROPERTYVALUE
error	Error creating ProviderClient: You must supply a Username in your AuthOptions."

I think at a minimum the error should be more friendly. In the bigger picture, this ties into whether a "default' profile (and/or the only defined profile if there is one) should be consumed by default when a profile isn't specified. It feels a little weird to use configure to make a config file, but then have to specify it all of the time with the --profile flag if it's the only one you're using. We could either hint in the configure process about using Default, or make it dummy proof by automatically consuming the profile if there is only a single profile saved. Actually both are probably good ideas. (Says the guy who suggested them.)

**Comment by jrperritt** [comment]
The error could be improved, but this isn't a bug. A username is required, whether it comes from the command-line, the config file, or the environment variable. Not specifying a `profile` will use the default profile if it exists. If creating a config file with `rack configure`, leaving the profile name blank will correctly create the default profile. I think using a named profile that isn't explicitly defined with the `profile` flag is counterintuitive.

**Comment by rtgoodwin** [comment]
I agree at the very least it's just an ask to improve the error, thus
enhancement not bug. The rest is merely opinionated speculation on my part
:)

**Comment by jrperritt** [comment]
I think you're right though that the `rack configure` introduction should better explain how profiles work.

**Comment by kenperkins** [comment]
I think we should re-title this issue, or create a different issue to track _pretty formatting of expected errors_.

Thoughts?

**Comment by rtgoodwin** [comment]
Here's my rough suggestion on improving this output:

"Error: Rackspace Cloud credentials are required, and you haven’t created a config file,  exported any environment variables, or specified them on the command line. You can fix this by
- running 'rack config' to create a configuration file
- specify the credentials in the command using --user, --apikey and --region
- export the required environment variables:
VAR1
VAR2
etc.

"

**Comment by rgbkrk** [comment]
I like @rtgoodwin's suggested message. Bonus would be if we let them know which they're missing if we have some of the environment variables (or some of the config).

**Comment by jrperritt** [comment]
Actually, Gophercloud already let's us know: 
```
"PROPERTYVALUE
error Error creating ProviderClient: You must supply a Username in your AuthOptions."
```
The only question is whether we create a hack to grep for the parts we want (like "Username") or do it correctly and implement error types in and return error types from in Gophercloud.

**Comment by rtgoodwin** [comment]
Can the client not check for presence of flags/file/bars on its own? It
doesn't seem that gopher cloud would want to absorb these changes that are
specific to the CLI?
