### ISSUE TITLE
Figure out flag names for resouces

### ISSUE THREAD

**Issue by kenperkins** [jrperritt/rack#90]
There is an open question about what the flag used to identify a resource should be called. In #86 @jrperritt has set it up so it's always the same as the resource argument in the command.

For example, if your command is `rack files container get` the flag will always be `--container`. This was proposed to eliminate a contention when doing `file` commands where you *always* specify a container.

```
rack files container get --name my-container
rack files object get --container my-container --name my-file.txt
```

By contrast, in #86 @jrperritt has set this to be like so:

```
rack files container get --container my-container
rack files object get --container my-container --object my-file.txt
```

This is great for calls where you have to reference more than one resource in the call, but it makes single resource calls a bit less elegant. For example, `instance` or `keypair` methods feel less intuitive:

```
rack servers instance get --instance my-instance-name
rack servers keypair generate --keypair my-keypair-name
```

These feel subjectively clunkier to me versus the shortened example:

```
rack servers instance get --name my-instance-name
rack servers keypair generate --name my-keypair-name
```

But even `keypair` can be contentious as `name` as it's used when creating an instance:

```
rack servers instance create --name my-server-name --keypair my-keypair-name --other flags here
```

Thoughts?

**Comment by kenperkins** [comment]
@jrperritt I think e3b4517 switched this to always use `name` when in context, and resource name, i.e. `keypair` when used out of context.

**Comment by jrperritt** [comment]
Yes, that's how it is now, by way of suggestion from @kenperkins

**Comment by kenperkins** [comment]
Are we leaving this open for discussion from others?

**Comment by jrperritt** [comment]
I'm indifferent. I'll close and if someone doesn't like the current implementation we can re-open.
