### ISSUE TITLE
Change user-agent to be unique

### ISSUE THREAD

**Issue by jnoller** [jrperritt/rack#92]
The user agent should be rackcli <version>

**Comment by jnoller** [comment]
Ugh GitHub stripped off the full piece - "rackcli (version)" or something equivalent

**Comment by jnoller** [comment]
Should include platform

**Comment by jrperritt** [comment]
Changed here: https://github.com/jrperritt/rack/commit/5162eb50d33a62909434d45ab91c8b04d8d74937

Now, for example, my `rack` user-agent is this: `rackcli-linux/0.0.0-dev gophercloud/1.0.0`
