### ISSUE TITLE
Always pass full=true to gophercloud for files object list

### ISSUE THREAD

**Issue by kenperkins** [jrperritt/rack#97]
Instead of only showing name on `rack files object list --container foo`, we should always return the full table, i.e. implicitly pass `full=true` to gophercloud's underlying API. 

If the user only wants names, we would use the `--fields name` syntax as with other apis, and if the only field is `name`, then we could make the optimized call.

Thoughts?

**Comment by kenperkins** [comment]
Ditto for `rack files container list`

**Comment by jrperritt** [comment]
Implemented here: https://github.com/jrperritt/rack/commit/0353a4b9ecc353a7f69d8db5fa696d894bb0b425

**Comment by kenperkins** [comment]
:heart: @jrperritt so much nicer.

**Comment by jrperritt** [comment]
I agree. Great suggestion @kenperkins
